name: deploy-container

on:
  push:
    branches: ["master"]
    paths:
      - "second-project/container/**"

defaults:
  run:
    working-directory: second-project/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install -f
      - run: npm run build
